In [ ]:
%matplotlib inline


PyTorch是什么?
================

基于Python的科学计算包，服务于以下两种场景:

-  作为NumPy的替代品，可以使用GPU的强大计算能力
-  提供最大的灵活性和高速的深度学习研究平台
    

开始
---------------

Tensors（张量）

Tensors与Numpy中的 ndarrays类似，但是在PyTorch中
Tensors 可以使用GPU进行计算.



In [8]:
from __future__ import print_function
import torch

创建一个 5x3 矩阵, 但是未初始化:



In [9]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


创建一个随机初始化的矩阵:



In [10]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8300, 0.2391, 0.2338],
        [0.1841, 0.0293, 0.8245],
        [0.1035, 0.9708, 0.6200],
        [0.8318, 0.5705, 0.5956],
        [0.9459, 0.9020, 0.3775]])


创建一个0填充的矩阵，数据类型为long:



In [11]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


创建tensor并使用现有数据初始化:



In [12]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


根据现有的张量创建张量。 这些方法将重用输入张量的属性，例如， dtype，除非设置新的值进行覆盖

In [18]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 方法来创建对象,dtype=torch.double是做什么的？
print(x)
print(type(x))
x = torch.randn_like(x, dtype=torch.float)    # 覆盖 dtype!
print(x)                                      # 对象的size 是相同的，只是值和类型发生了变化
print(type(x))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
<class 'torch.Tensor'>
tensor([[-0.2605,  0.4879,  0.1612],
        [ 0.4729,  0.0216,  1.0808],
        [-0.1251, -1.1892, -0.8105],
        [-1.2080,  1.0302,  0.9844],
        [-0.5773,  0.2125,  0.1674]])
<class 'torch.Tensor'>


获取 size

***译者注：使用size方法与Numpy的shape属性返回的相同，张量也支持shape属性，后面会详细介绍***


In [19]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` 返回值是 tuple类型, 所以它支持tuple类型的所有操作.</p></div>

操作

操作有多种语法。 

我们将看一下加法运算。

加法1:

In [26]:
y = torch.rand(5, 3)
print(y)
print(x + y)

tensor([[0.8705, 0.6736, 0.6667],
        [0.6675, 0.3350, 0.2287],
        [0.2445, 0.8014, 0.3073],
        [0.0322, 0.8656, 0.1753],
        [0.3116, 0.9567, 0.3343]])
tensor([[ 0.6099,  1.1615,  0.8279],
        [ 1.1403,  0.3566,  1.3095],
        [ 0.1194, -0.3878, -0.5032],
        [-1.1758,  1.8957,  1.1597],
        [-0.2658,  1.1693,  0.5018]])


加法2


In [21]:
print(torch.add(x, y))

tensor([[ 0.2142,  0.8852,  0.9644],
        [ 0.9035,  0.3870,  1.5749],
        [ 0.7613, -0.2382, -0.1635],
        [-0.6445,  1.5564,  1.1941],
        [ 0.0463,  0.6234,  0.6744]])


提供输出tensor作为参数



In [22]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.2142,  0.8852,  0.9644],
        [ 0.9035,  0.3870,  1.5749],
        [ 0.7613, -0.2382, -0.1635],
        [-0.6445,  1.5564,  1.1941],
        [ 0.0463,  0.6234,  0.6744]])


替换



In [25]:
# adds x to y   ； 把x加到y上并存为新的y
print(y)
print(x)
y.add_(x)
print(y)

tensor([[-0.0463,  1.3731,  1.1256],
        [ 1.3763,  0.4086,  2.6557],
        [ 0.6362, -1.4274, -0.9740],
        [-1.8525,  2.5865,  2.1785],
        [-0.5310,  0.8359,  0.8418]])
tensor([[-0.2605,  0.4879,  0.1612],
        [ 0.4729,  0.0216,  1.0808],
        [-0.1251, -1.1892, -0.8105],
        [-1.2080,  1.0302,  0.9844],
        [-0.5773,  0.2125,  0.1674]])
tensor([[-0.3068,  1.8611,  1.2868],
        [ 1.8492,  0.4301,  3.7364],
        [ 0.5111, -2.6166, -1.7845],
        [-3.0605,  3.6167,  3.1629],
        [-1.1083,  1.0485,  1.0093]])


<div class="alert alert-info"><h4>Note</h4><p>任何 以``_`` 结尾的操作都会用结果替换原变量.
    例如: ``x.copy_(y)``, ``x.t_()``, 都会改变 ``x``.</p></div>

你可以使用与NumPy索引方式相同的操作来进行对张量的操作



In [30]:
print(x,end='\n\n')
print(x[:, 1])

tensor([[-0.2605,  0.4879,  0.1612],
        [ 0.4729,  0.0216,  1.0808],
        [-0.1251, -1.1892, -0.8105],
        [-1.2080,  1.0302,  0.9844],
        [-0.5773,  0.2125,  0.1674]])

tensor([ 0.4879,  0.0216, -1.1892,  1.0302,  0.2125])


``torch.view``: 可以改变张量的维度和大小

***译者注：torch.view 与Numpy的reshape类似***



In [43]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  #  size -1 从其他维度推断
print('x',x,end='\n\n')
print('y',y,end='\n\n')
print('z',z,end='\n\n')
print(x.size(), y.size(), z.size())

x tensor([[ 2.8603e-01, -2.0846e+00,  2.0022e-02,  1.3453e+00],
        [-1.8854e-01,  1.1079e+00, -2.8481e-01,  4.9619e-01],
        [ 2.2971e-01, -1.8633e+00, -1.1108e-03, -5.7771e-01],
        [ 1.7977e+00, -6.3513e-01,  5.1092e-01, -1.3669e+00]])

y tensor([ 2.8603e-01, -2.0846e+00,  2.0022e-02,  1.3453e+00, -1.8854e-01,
         1.1079e+00, -2.8481e-01,  4.9619e-01,  2.2971e-01, -1.8633e+00,
        -1.1108e-03, -5.7771e-01,  1.7977e+00, -6.3513e-01,  5.1092e-01,
        -1.3669e+00])

z tensor([[ 2.8603e-01, -2.0846e+00,  2.0022e-02,  1.3453e+00, -1.8854e-01,
          1.1079e+00, -2.8481e-01,  4.9619e-01],
        [ 2.2971e-01, -1.8633e+00, -1.1108e-03, -5.7771e-01,  1.7977e+00,
         -6.3513e-01,  5.1092e-01, -1.3669e+00]])

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果你有只有一个元素的张量，使用``.item()``来得到Python数据类型的数值


In [44]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.6724])
0.6723853349685669


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy 转换
------------

将一个Torch Tensor转换为NumPy数组是一件轻松的事，反之亦然。

Torch Tensor与NumPy数组共享底层内存地址，修改一个会导致另一个的变化。

将一个Torch Tensor转换为NumPy数组



In [45]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [46]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


观察numpy数组的值是如何改变的。



In [47]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


 NumPy Array 转化成 Torch Tensor

使用from_numpy自动转化



In [48]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)



所有的 Tensor 类型默认都是基于CPU， CharTensor 类型不支持到
NumPy 的转换.
CUDA 张量
------------

使用``.to`` 方法 可以将Tensor移动到任何设备中



In [53]:
# is_available 函数判断是否有cuda可以使用
# ``torch.device``将张量移动到指定的设备中

if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 直接从GPU创建张量
    x = x.to(device)                       # 或者直接使用``.to("cuda")``将张量移动到cuda中
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 也会对变量的类型做更改
else:print('no cuda')

no cuda
